name: "Fetch spreadsheet data"
description: "Get data from spreadsheets"

author: "chronoscore622"
inputs:
  data:
    description: "fetched data"
    required: true

outputs:
  result:
    description: "the fetched data in json??"

runs:
  using: "node24"
  main: "dist/index.js"
